services:
  - type: web
    name: MemoEthiopa
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn MemoEthiopa.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: MemoEthiopa-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
